services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - webmosh-db:/var/lib/postgresql/data

volumes:
  webmosh-db:
